# Generated by Django 3.0.3 on 2020-02-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0002_categoria_comentario_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carrinhos', models.ManyToManyField(related_name='produtos', to='aula5.Carrinho')),
            ],
        ),
    ]
