# Generated by Django 3.0.3 on 2020-02-29 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula5', '0004_auto_20200229_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='carrinhos',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='carrinho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aula5.Carrinho'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
